#### Import NumPy as np

In [2]:
import  numpy as np

In [ ]:
# np.newaxis()

#### Create an array of 10 zeros

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [19]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [26]:
np.random.rand()

0.6623610188158005

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution


In [28]:
np.random.randn(25)

array([ 0.48932607, -1.0739285 ,  0.08806287, -0.99760627,  0.58807665,
        0.05460123,  0.20593828, -0.8506807 ,  0.71229784,  0.04330655,
       -0.64520498, -2.26392165,  0.48836813, -0.38554113,  1.11951779,
       -1.08439714,  0.33750241, -0.61428539,  0.32128526,  0.77225228,
       -0.87592199,  0.40650059,  1.22153001,  0.80557514,  2.60876342])

#### Create an array of 10x10 with stepsize 0.01

In [39]:
np.arange(0,1,0.01).reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

#### Create an array of 20 linearly spaced points between 0 and 1

In [41]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Numpy indexing and Selection

In [131]:
mat = np.arange(1,26).reshape(5,5)
mat
mat[2:,1:]
mat[3,4]
mat[:3,[1]]
mat[4]
mat[3:]
mat.sum()
mat.std()
mat.sum(axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Print the numpy version and the configuration

In [65]:
np.version.version

'1.18.1'

In [70]:
np.show_config()

#### Create a null vector of size 10 

In [78]:
x=np.arange(10)

#### How to find the memory size of any array 

In [80]:
x.size*x.itemsize

40

#### Create a null vector of size 10 but the fifth value which is 1

In [81]:
z=np.zeros(10)
z[5]=1

#### Create a vector with values ranging from 10 to 49

In [83]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Reverse a vector (first element becomes last) 

In [84]:
a=np.arange(10)
a[10::-1]

#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [88]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

#### Create a 3x3x3 array with random values

In [95]:
from numpy.random import randint as ri
ri(1,100,27).reshape(3,3,3)

array([[[66, 25, 87],
        [51, 85, 43],
        [41, 24, 34]],

       [[27,  8, 83],
        [70, 99, 32],
        [79, 74, 99]],

       [[56, 26, 81],
        [16, 34, 25],
        [82, 42,  3]]])

#### Create a 10x10 array with random values and find the minimum and maximum values

In [97]:
a=ri(0,100,100).reshape(10,10)
a.max()
a.min()

#### Create a random vector of size 30 and find the mean value

In [102]:
a=ri(0,100,30)
a.mean()

#### Create a 2d array with 1 on the border and 0 inside

In [116]:
a=np.ones([5,5])
a[1:4,1:4]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### How to add a border (filled with 0's) around an existing array?

In [145]:
a=np.arange(9).reshape(3,3)
np.pad(a,1)

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]])

#### What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [243]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [110]:
np.diagflat([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Create a 8x8 matrix and fill it with a checkerboard pattern

In [144]:
a=np.ones([8,8],dtype=int)
a[1::2,::2]=0
a[::2,1::2]=0
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [252]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [253]:
# np.where(a==99)

#### Create a checkerboard 8x8 matrix using the tile function

In [165]:
a=np.array([[1,0],[0,1]])
np.tile(a,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### Normalize a 5x5 random matrix

In [190]:
a=np.random.random((5,5))
amax,amin=a.max(),a.min()
a=(a-amin)/(amax-amin)
a

array([[0.43217573, 1.        , 0.10769399, 0.64350992, 0.82418027],
       [0.34854098, 0.68407226, 0.48298876, 0.85039229, 0.40403209],
       [0.3760706 , 0.71681187, 0.85766515, 0.13601146, 0.27060916],
       [0.19965111, 0.12591692, 0.        , 0.95174199, 0.73955326],
       [0.79695669, 0.3852469 , 0.68784746, 0.97621906, 0.22513784]])

#### Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [255]:
np.dtype([('RGBA', np.uint32)])

dtype([('RGBA', '<u4')])

#### Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [191]:
a=np.mat(np.random.random((5,3)))
b=np.mat(np.random.random((3,2)))
a*b

#### Given a 1D array, negate all elements which are between 3 and 8, in place

In [224]:
a=np.arange(20,dtype=int)

In [257]:
b=a>3,a<8

#### What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [234]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [236]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

#### How to round away from zero a float array ?

In [278]:
a=np.array([1.223,2.342,3.431,4.4235])
# np.copysign(a)
#np.uniform(a)
# np.ceil(a)
# np.abs(a,)
np.around(a,2)
# np.floor(a)

array([1.22, 2.34, 3.43, 4.42])

#### How to find common values between two arrays?

In [285]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([4,5,6,6,7,8,9,0])
np.intersect1d(a,b)

array([4, 5, 6, 7])

#### How to ignore all numpy warnings (not recommended)?

#### Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [289]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\rajat-negi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### How to get the dates of yesterday, today and tomorrow?

In [14]:
yesterday= np.datetime64("today")-np.timedelta64(1)
print("yesterday: ",yesterday)
today=np.datetime64("today")
print("today: ",today)
tomorrow=np.datetime64("today")+np.timedelta64(1)
print("tomorrow: ",tomorrow)

yesterday:  2020-05-15
today:  2020-05-16
tomorrow:  2020-05-17


#### How to get all the dates corresponding to the month of July 2016?

In [24]:
# print(np.arange('2016-7','2016-8',dtype='datetime64[D]'))

#### How to compute ((A+B)*(-A/2)) in place (without copy)?

In [32]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
((A+B)*(-A/2))

array([ -3.,  -8., -15., -24.])

#### Extract the integer part of a random array using 5 different methods

In [43]:
import pandas as pd
a=([1.46,2.6754,3.343,4.004,5.324])
# np.floor(a)
# np.ceil(a)
# pd.astype(a,int32)

#### Create a 5x5 matrix with row values ranging from 0 to 4

In [48]:
np.ones([5,5])*np.array([0,1,2,3,4])

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Consider a generator function that generates 10 integers and use it to build an array

In [54]:
# iteration=[x for x in range(10)]
# np.fromiter(iteration,int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [70]:
# import numpy as np
# x = np.linspace(0,1,12,endpoint=True)[1:-1]
# print(x)
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### Create a random vector of size 10 and sort it

In [73]:
from numpy.random import randint as ri
a=ri(1,100,10)
a.sort()
a

array([10, 16, 21, 30, 31, 36, 69, 79, 82, 90])

#### How to sum a small array faster than np.sum?

In [75]:
np.add.reduce(a)

464

#### Consider two random array A and B, check if they are equal

In [77]:
b=ri(1,100,10)
a==b

array([False, False, False, False, False, False, False, False, False,
       False])

#### Make an array immutable (read-only)

In [81]:
x=np.ones(10)
x.flags.writeable=False
# x[0]=1

#### Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [97]:
c=np.random.random((10,2))
x,y=c[:,1],c[:,0]
r=np.sqrt(x**2+y**2)
t=np.arctan2(x,y)
print(r)
print(t)

[0.11796815 0.57668422 1.17054592 1.02569765 0.67262736 0.67130655
 0.75339015 0.83240383 0.66488237 0.82436037]
[0.32815019 1.30295363 0.95157799 0.39097221 0.68338739 0.63057988
 1.22639356 0.25915456 0.03822781 0.43753312]


#### Create random vector of size 10 and replace the maximum value by 0

In [110]:
x=np.random.random(10)
x[x.argmin()]=0
x

array([0.43884979, 0.51674789, 0.27163545, 0.        , 0.0765221 ,
       0.83816369, 0.8271151 , 0.8812897 , 0.25001156, 0.52107656])

#### Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [12]:
def kangaroo(x1, v1, x2, v2):
    for i in range(100):
        if (x1>x2 and v1>v2) or (x2>x1 and v2>v1):
            return 'NO'
     
kangaroo(1,4,1,2)

#### Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### Print the minimum and maximum representable value for each numpy scalar type

#### How to print all the values of an array? 

#### How to find the closest value (to a given scalar) in a vector?

#### Create a structured array representing a position (x,y) and a color (r,g,b)

#### Consider a random vector with shape (100,2) representing coordinates, find point by point distances

#### How to convert a float (32 bits) array into an integer (32 bits) in place?

#### How to read the following file? 
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

#### What is the equivalent of enumerate for numpy arrays? 

#### Generate a generic 2D Gaussian-like array

#### How to randomly place p elements in a 2D array?

#### Subtract the mean of each row of a matrix

#### How to sort an array by the nth column? 

#### How to tell if a given 2D array has null columns?

#### Find the nearest value from a given value in an array

#### Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

#### Create an array class that has a name attribute 

#### Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

#### How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

#### Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

#### Considering a four dimensions array, how to get sum over the last two axis at once?

#### Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

#### How to get the diagonal of a dot product?

#### Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

#### How to swap two rows of an array?

#### Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

#### Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

#### How to compute averages using a sliding window over an array?

#### Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### How to negate a boolean, or to change the sign of a float inplace?

#### Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

#### Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

#### Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

#### Compute a matrix rank

#### How to find the most frequent value in an array?

#### Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

#### Create a 2D array subclass such that Z[i,j] == Z[j,i] 

#### Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 

#### How to implement the Game of Life using numpy arrays?

#### How to get the n largest values of an array

#### Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

##### How to create a record array from a regular array?

#### Consider a large vector Z, compute Z to the power of 3 using 3 different methods 

##### Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?


##### Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

#### Convert a vector of ints into a matrix binary representation

#### Given a two dimensional array, how to extract unique rows?

#### Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 

#### Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 

#### Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elementsof an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
